### ISSUE TITLE
AuthoringRole

### ISSUE THREAD

**Issue by sballesteros** [scienceai/scholarly-article#15]
## Use case

See https://github.com/scienceai/scholarly.vernacular.io/issues/32
In 2015, Peter was affiliated with Princeton and Harvard but wrote a Scholarly article only involving his Princeton affiliation.

### new `schema:Role` subclass: `sa:AuthoringRole`
```
{
  "@id": "sa:AuthoringRole",
  "@type": "rdfs:Class",
  "label": "Authoring Role",
  "comment": "A subclass of Role used to describe authoring roles.",
  "subClassOf": [
    "http://schema.org/Role"
  ],
  "source": "https://github.com/scienceai/scholarly.vernacular.io/issues/32",
  "status": "testing"
}
```

### associated `sa:roleAffiliation` property
```
{
  "@id": "sa:roleAffiliation",
  "@type": "rdf:Property",
  "comment":"The affiliation under which the role was performed.",
  "label": "role affiliation",
  "range": "schema:Organization",
  "domain": "sa:AuthoringRole",
  "source": "https://github.com/scienceai/scholarly.vernacular.io/issues/32",
  "status": "testing"
}
```

## Example

```
{
  "@id": "http://example.com/article",
  "@type": "schema:ScholarlyArticle",
  "author": {
    "@type": "sa:AuthoringRole",
    "author": {
      "@id": "http://example.com/peter",
      "@type": "schema:Person",
      "affiliation": [
        {"@id": "http://www.princeton.edu"},
        {"@id": "http://www.harvard.edu/"}
      ]
    },
    "roleAffiliation": {
      "@id": "http://www.princeton.edu",
      "@type": "schema:CollegeOrUniversity",
      "name": "Princeton University"
    }
  }
}
```

cc: @darobin @pjohnston-wiley

**Comment by pjohnston-wiley** [comment]
I like this, it corresponds to our model. 

In a real-world article, the affiliation property of AuthoringRole will likely not be used. We might collect different affiliations over time from articles, or independently from the individual themselves, and these could be made available in a Person context by interrogating the Person resource itself. It's not normally the place of an article to collect all the person's affiliations.

What we might actually want to include here is a correspondence address. This does belong to the Person, but it is one of several addresses they may have, and they may use different addresses for different contexts. It may also differ from the address of the affiliation, since the research may have been carried out elsewhere, or the person has since moved on. Therefore, i would suggest adding xxx:correspondenceAddress thus: 

```json
    {
      "@id": "http://example.com/article",
      "@type": "schema:ScholarlyArticle",
      "author": {
        "@type": "sa:AuthoringRole",
        "author": {
          "@id": "http://example.com/peter",
          "@type": "schema:Person"
        },
        "roleAffiliation": {
          "@id": "http://www.princeton.edu",
          "@type": "schema:CollegeOrUniversity",
          "name": "Princeton University"
        } ,
        "xxx:correspondenceAddress": {
             "@id": "http://example.com/peter/currentCorrespondenceAddress",
             "@type": "schema:PostalAddress",
            ....
        }
      }
    }
```

**Comment by sballesteros** [comment]
Still thinking on `correspondenceAddress`...

**Comment by sballesteros** [comment]
ok so we went with 

```
    {
      "@id": "sa:roleContactPoint",
      "@type": "rdf:Property",
      "comment": "A contact point for the person or organization behind an authoring role.",
      "label": "role contact point",
      "range": "schema:ContactPoint",
      "domain": "sa:AuthoringRole",
      "source": "https://github.com/scienceai/scholarly.vernacular.io/issues/32",
      "status": "testing"
    },
```

as most of the time an `email` will be enough. Note that we can have access to a full `PostalAdress` as `PostalAddress` is a subclass of `ContactPoint`.

I will add that to http://scholarly.vernacular.io/.
Thanks a lot for the feedback @pjohnston-wiley !

**Comment by darobin** [comment]
Alternatively, we could use the phd ontology: http://www.phdcomics.com/comics.php?f=562

**Comment by pjohnston-wiley** [comment]
It still bothers me that `schema:Role` subclasses are somewhat fluffy. The underlying [assertion](http://blog.schema.org/2014/06/introducing-role.html)) seems to be that the Role class can be used to qualify all properties for a specific domain, or a specific property. By convention the property used is repeated against the Role (a resource-oriented version of the `rdf:value` convention). However, none of this is encoded anywhere. 

So, OrganizationRole qualifies any property that has an Organization as domain. EmployeeRole specifically qualifies the `employee` property, PerformanceRole the `actor` property. For example, the intent is, i assume, not to enable:

```turtle
<organization> schema:award <employeeRole> .
<employeeRole> a schema:EmployeeRole ;
  schema:award <person> ;
  schema:baseSalary "3s4p" .
```
The naming conventions are then inconsistent (PerformanceRole should really be `ActorRole`), which wouldn't be bad if i had a formal way of determining its scope, and hence what i can usefully do with it. It would just be much simpler if the scope of properties were explicitly extended to include the relevant role subclasses. It just seems incongruous when other things are strictly scoped, for example a `schema:Article` gets a pageStart and a pageEnd, but only `schema:Book` gets a numberOfPages, which discounts the possibility of advertising pages in a magazine article.

If i assume for now that this encoding is implicit, and try to normalize the conventions, `AuthoringRole` should really be called either `CreativeWorkRole` or `AuthorRole`, because its intent is either to qualify any property of a creative work, or to qualify the author property. By allowing a contactPoint, we are really restricting to the `author` property, so `AuthorRole` would fit better. You could also say that this construct might apply equally to `schema:contributor`, and if you consider `schema:author` to be a special case of that, `ContributorRole` might be more appropriate. Again, a more explicit encoding would help.

**Comment by pjohnston-wiley** [comment]
@darobin have you thought of changing the name of the software to 'postdoc', that way professors would be more comfortable using it....

**Comment by sballesteros** [comment]
Good point `ContributorRole` is a better name.

**Comment by sballesteros** [comment]
@darobin ok with the change `AuthoringRole` -> `ContributorRole` ?
